### ISSUE TITLE
Allow boolean expressions to work with python `and` and `or`.

### ISSUE THREAD

**Issue by PeerHeer** [reapermc/wicked-expressions#35]
Implement using `__dup__`, `__rebind__`, `__not__` and `__branch__`.  
It should also work with `.exists()`!

# Example
## AND
```py
if a and b:
    # if
else:
    # else
```
```py
t0 = a.__dup__()
if t0:        # t0.__branch__()
    t0 = b    # t0.__rebind__(b)
# t0 = a and b
if t0:        # t0.__branch__()
    # if
t1 = not t0   # t1.__rebind__(t0.__not__())
if t1:        # t1.__branch__()
    # else
```

## OR
```py
if a or b:
    # if
else:
    # else
```
```py
t0 = a.__dup__()
if not a:
    t0 = b    # t0.__rebind__(b)
# t0 = a or b

if t0:        # t0.__branch__()
    # if
t1 = not t0   # t1.__rebind__(t0.__not__())
if t1:        # t1.__branch__()
    # else
```

# TODO
- [ ] Implement `__rebind__` for `BooleanOperation` and `BinaryOperation`
- [ ] Implement `__dup__` for `ScoreSource`, `DataSource`, `BooleanOperation` and `BinaryOperation`
- [ ] make it work lmao
